SELECT TOP 1 WITH TIES D1_FILIAL, D1_PEDIDO, D1_DTDIGIT
FROM SD1010
WHERE D_E_L_E_T_ <> '*' AND D1_PEDIDO <> ''
ORDER BY
ROW_NUMBER() OVER(PARTITION BY D1_FILIAL, D1_PEDIDO, D1_DTDIGIT ORDER BY D1_FILIAL, D1_PEDIDO, D1_DTDIGIT)
